version: "3"
services:
  server:
    image: com.suan/hys-test/resource-server
    container_name: hys-test-server
    ports:
      - "8081:8081"
    environment:
      ISSUER_URI: ${ISSUER_URI}
      JWK_SET_URI: ${JWK_SET_URI}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 2
  client:
    image: com.suan/hys-test/client
    container_name: hys-test-client
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      ISSUER_URI: ${ISSUER_URI}
      RESOURCE_URI: ${RESOURCE_URI}
